### ISSUE TITLE
Not an issue. I couldn't make a pull request, so here it is :p

### ISSUE THREAD

**Issue by Diegitx** [SmallJoker/EE_CM_server#2]
I want to put a tutorial-like build area for the world http://krock-works.16mb.com/rd.php?w=PWlecg8I . Can someone allow me to do it? And i want a kinda boss bot for ee cm too :D TherealHG can tell you what it is ;)

**Comment by SmallJoker** [comment]
This is the server source code. First of all, this requires a new feature if you want such an area-specific edit access for people in a world. There is nothing like that in the source code right now, so I can not allow something that does not exist.
