### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by arkadiusz1234** [SmallJoker/EE_CM_server#9]
How do we use this code to make an private server?

**Comment by SmallJoker** [comment]
1) Set up a PlayerIO account (however it is called now)
2) Create a new game ID in PlayerIO
3) Compile this stuff
4) Upload the binary (*.dll)
5) Download an EE CM flash file (stripped PayVault)
6) Edit the room types with the free flash decompiler
7) Test & pray

End of support.

**Comment by arkadiusz1234** [comment]
Uh if i could get the EE CM flash file. Cannot find anything.

**Comment by Vaela-V** [comment]
You're looking in the wrong places probably, it isn't just a simple search
away. Try using archive sites if you're really struggling to find the old
one, however if you haven't found anything regarding it then you've
probably skipped a few important places.

**Comment by arkadiusz1234** [comment]
Your right i was searching in wrong place. I found it .

**Comment by arkadiusz1234** [comment]
Maybe im asking for too much. How do i add admins?
